//signup the user
POST http://localhost:3000/signupUser/ 
Content-Type: application/json

{
    "username":"sahith23",
    "name":"sai sahith",
    "password":"sahith07",
    "gender":"male",
    "location":"khammam"
}

###
//login the user and get jwt token
post http://localhost:3000/login/
Content-Type: application/json

{
  "username": "sahith23",
  "password": "sahith07"
}
###
//get all the activeCases in India
GET http://localhost:3000/activeCases/
Authorization: Header eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaGl0aDIzIiwiaWF0IjoxNjMwODI3OTMzfQ.uK_D93LcAKL5vqTYl-V3d2XHkmg0xMe-_w-2dLvM3hA

###

//get all the totalCases in India

GET http://localhost:3000/totalCases/
Authorization: Header eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaGl0aDIzIiwiaWF0IjoxNjMwODI3OTMzfQ.uK_D93LcAKL5vqTYl-V3d2XHkmg0xMe-_w-2dLvM3hA
###

//get all the curedCases in India

GET http://localhost:3000/cured/
Authorization: Header eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaGl0aDIzIiwiaWF0IjoxNjMwODI3OTMzfQ.uK_D93LcAKL5vqTYl-V3d2XHkmg0xMe-_w-2dLvM3hA
###

GET http://localhost:3000/books/


###

//get the data of selected type of cases select=(cured,active,cases) 
//we can get which state has orderby=DESC(top cases) and ASC(least cases)
//we can set limit and offset
GET http://localhost:3000/selected/?offset=0&limit=10&order=ASC&select=cured
Authorization: Header eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaGl0aDIzIiwiaWF0IjoxNjMwODI3OTMzfQ.uK_D93LcAKL5vqTYl-V3d2XHkmg0xMe-_w-2dLvM3hA

###

GET http://localhost:3000/searchStates/
Authorization: Header eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaGl0aDIzIiwiaWF0IjoxNjMwODI3OTMzfQ.uK_D93LcAKL5vqTYl-V3d2XHkmg0xMe-_w-2dLvM3hA
Content-Type: application/json

{
    "stateName":"an"
}

###

GET http://localhost:3000/searchDistrict/
Authorization: Header eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhaGl0aDIzIiwiaWF0IjoxNjMwODI3OTMzfQ.uK_D93LcAKL5vqTYl-V3d2XHkmg0xMe-_w-2dLvM3hA
Content-Type: application/json

{
    "districtName":"krishna"
}